### ISSUE TITLE
Modify Miscellaneous System - Base URL of the service

### ISSUE THREAD

**Issue by arodriguezd** [kurokobo/awx-on-k3s#111]
## Environment

- OS: Ubuntu 20.04.x 
- K3s: v1.23.8+k3s2
- AWX Operator: 0.25.0

## Description

I am trying to change the "Base URL of the service" option in the Settings - Miscellaneous System tab, right now it shows me the option of:

https://towerhost

When trying to change the UI gives me an error that does not let me perform any action, I have seen that it is already reported in the awx issue,

https://github.com/ansible/awx/issues/10565

Could this option be added in the awx.yaml can it be added?

  because I am trying to configure "Base URL of the service", because when configuring the Authentication Azure AD, it shows me the following option:

Azure AD OAuth2 Callback URL
https://towerhost/sso/complete/azuread-oauth2/

And I need to change the towehost to the domain that I am using.

## Step to Reproduce

I have followed the steps of the configuration, I am using a wildcard certificate and take from http to https and the proxy

I add the awx.yaml file that I used

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  # These parameters are designed for use with:
  # - AWX Operator: 0.25.0
  #   https://github.com/ansible/awx-operator/blob/0.25.0/README.md
  # - AWX: 21.3.0
  #   https://github.com/ansible/awx/blob/21.3.0/INSTALL.md

  admin_user: admin
  admin_password_secret: awx-admin-password

  ingress_type: ingress
  ingress_tls_secret: awx-secret-tls
  hostname: awx-test.domain.com
  bundle_cacert_secret: awx-custom-certs

  

  ingress_annotations: |
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd

  extra_settings:
    - setting: REMOTE_HOST_HEADERS
      value: "['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'REMOTE_HOST']"

  postgres_configuration_secret: awx-postgres-configuration

  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 10Gi

  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}

  # Uncomment to reveal "censored" logs
  #no_log: "false"
```
Has anyone had a similar problem?
I've been looking for what script or file would generate that hostname but I haven't been able to find it.

**Comment by kurokobo** [comment]
@arodriguezd 
Hi, thanks for using my repo 😃 

Sadly, using `extra_settings` in `awx.yaml` sometimes prevent us from using `Edit` button on some setting pages. In your case, I think `REMOTE_HOST_HEADERS` is the cause of `Something went wrong`.

You have two choices:

1. Add `TOWER_URL_BASE` in addition to `REMOTE_HOST_HEADERS` under `extra_settings`, and `kubectl apply -k base` again then wait for re-deployment.
     ```yaml
     ...
     extra_settings:
       - setting: REMOTE_HOST_HEADERS
         value: "['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'REMOTE_HOST']"
       - setting: TOWER_URL_BASE     👈👈👈
         value: "'https://awx.example.com'"     👈👈👈
     ```
   - `TOWER_URL_BASE` is for `Base URL of the service`. You should take care of usage of quotation; `"'<value>'"`.
   - If your AWX Pod is not re-created after `kubectl apply`, invoke `kubectl -n delete pod awx-**********-*****` to force K3s to re-create it.
3. Stop using `extra_settings` in `awx.yaml` and modify appropriate settings through Web UI.
   - Remove `extra_settings` in your `awx.yaml` and invoke `kubectl apply -k base`, and wait for re-deployment.
   - `Edit` button on the settings page shoud work now. You can edit `Remote host headers` and `Base URL of the service`.
