### ISSUE TITLE
"Bad Gateway" issue

### ISSUE THREAD

**Issue by kcslb92** [kurokobo/awx-on-k3s#113]
Hi,

I've followed your tutorial to deploy awx into k3s on CentOS 8, when attempting to access awx I am getting "Bad Gateway" and can see in the awx-web pod that the issue is with regards to the Postgres database. I came across [this link](https://github.com/ansible/awx-operator/issues/848) and believe this is the same issue. Whilst I don't think this issue is related to this repo/tutorial, I am hoping that you may be able to provide some assistance in troubleshooting and any actions required to rectify it could be added to the tutorial?

```
[root@awx-02 awx-on-k3s]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOSStream
Description:	CentOS Stream release 8
Release:	8
Codename:	n/a

...

[root@awx-02 awx-on-k3s]# kubectl get nodes
NAME     STATUS   ROLES                  AGE     VERSION
awx-02   Ready    control-plane,master   6h23m   v1.24.3+k3s1

...

[root@awx-02 awx-on-k3s]# kubectl get pods -n awx
NAME                                               READY   STATUS    RESTARTS   AGE
awx-operator-controller-manager-7f89bd5797-g6xkg   2/2     Running   0          6h24m
awx-postgres-13-0                                  1/1     Running   0          6m6s
awx-5d7b85bc77-px5vh                               4/4     Running   0          5m53s

...

[root@awx-02 awx-on-k3s]# kubectl logs awx-5d7b85bc77-px5vh -n awx -c awx-web
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 30
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2 of 30
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3 of 30
[wait-for-migrations] Waiting 2 seconds before next attempt
[wait-for-migrations] Attempt 4 of 30
[wait-for-migrations] Waiting 4 seconds before next attempt
[wait-for-migrations] Attempt 5 of 30
[wait-for-migrations] Waiting 8 seconds before next attempt
[wait-for-migrations] Attempt 6 of 30
[wait-for-migrations] Waiting 16 seconds before next attempt
[wait-for-migrations] Attempt 7 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 8 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 9 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 10 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 11 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 12 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 13 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 14 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 15 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 16 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 17 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 18 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
```

Cheers!

**Comment by kcslb92** [comment]
It's worth adding that this was using 0.26.0 of the awx-operator.

**Comment by kurokobo** [comment]
@kcslb92 
Hi, thanks for filling the issue.

Are you using external PostgreSQL or managed one?

Typically this is the communication issue between AWX and PostgreSQL.

Refer [my troubleshooting guide](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/troubleshooting.md) and ensure your `firewalld` or any kind of firewall has been disabled on your K3s host.

**Comment by kcslb92** [comment]
Hi @kurokobo, thanks for the prompt response.

Managed PostgreSQL, I followed the deployment tutorial for this repo exactly, just that I'm using 0.26.0 operator instead of 0.25.0.

```
[root@awx-02 awx-on-k3s]# kubectl -n awx logs awx-postgres-13-0

PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-08-06 08:05:17.638 UTC [1] LOG:  starting PostgreSQL 13.7 (Debian 13.7-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-08-06 08:05:17.639 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-08-06 08:05:17.639 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-08-06 08:05:17.640 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-08-06 08:05:17.644 UTC [26] LOG:  database system was shut down at 2022-08-06 08:05:16 UTC
2022-08-06 08:05:17.648 UTC [1] LOG:  database system is ready to accept connections

...

[root@awx-02 awx-on-k3s]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

Aug 06 11:20:22 awx-02 systemd[1]: Starting firewalld - dynamic firewall daemon...
Aug 06 11:20:23 awx-02 systemd[1]: Started firewalld - dynamic firewall daemon.
Aug 06 11:20:23 awx-02 firewalld[1102]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
Aug 06 11:21:40 awx-02 systemd[1]: Stopping firewalld - dynamic firewall daemon...
Aug 06 11:21:41 awx-02 systemd[1]: firewalld.service: Succeeded.
Aug 06 11:21:41 awx-02 systemd[1]: Stopped firewalld - dynamic firewall daemon.
```

The `awx.yaml` and `customisation.yaml` files are as follows:

```
[root@awx-02 awx-on-k3s]# cat base/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres
      - port=5432
      - database=awx
      - username=awx
      - password=VMware1!
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=VMware1!

  # Temporary workaround to suppress errors from AWX Operator 0.21.0.
  # Refer: https://github.com/kurokobo/awx-on-k3s/issues/74
  - name: redhat-operators-pull-secret
    files:
      - .dockerconfigjson=dockerconfig.json
    type: kubernetes.io/dockerconfigjson

resources:
  - pv.yaml
  - pvc.yaml
  - awx.yaml
```

```
[root@awx-02 awx-on-k3s]# cat base/awx.yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  # These parameters are designed for use with:
  # - AWX Operator: 0.25.0
  #   https://github.com/ansible/awx-operator/blob/0.25.0/README.md
  # - AWX: 21.3.0
  #   https://github.com/ansible/awx/blob/21.3.0/INSTALL.md

  admin_user: admin
  admin_password_secret: awx-admin-password

  ingress_type: ingress
  ingress_tls_secret: awx-secret-tls
  hostname: awx-02.spicy.meatballs

  postgres_configuration_secret: awx-postgres-configuration

  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 8Gi

  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}

  # Uncomment to reveal "censored" logs
  #no_log: "false"
```

The last step in the troubleshooting guide for this issue is to `Uninstall K3s and install it again.`, would you advise I attempt this as the next step?

Cheers.

**Comment by kurokobo** [comment]
@kcslb92 
Try disabling your firewall and rebooting your host;

```bash
sudo systemctl disable firewalld --now
sudo reboot
```

If this can't solve your issue and if it's ok for you to wipe out whole your k3s-related environment (all namespaces, pvs, pods, secrets, etc.), please try uninstalling and installing k3s.

```bash
# Uninstall k3s
/usr/local/bin/k3s-uninstall.sh
sudo rm -rf /data/postgres

# Then install k3s and deploy awx operator and awx again by following my guide.
```

My response will be delayed due to family matters. Thanks for your patience.

**Comment by kcslb92** [comment]
Hi @kurokobo,

I had already disabled the firewall. 

Oddly enough when I uninstalled and reinstalled k3s it worked straight away, odd!

Thanks for your assistance.

**Comment by kurokobo** [comment]
I've never digged into this since I've never faced this but this seems to happen sometimes.

Anyway good to hear that your awx works. I'm closing this issue.

**Comment by kurokobo** [comment]
@kcslb92 
Hi, just for your information, I'm testing `0.26.0` in my environment and found that the `host` for PostgreSQL has to be `awx-postgres-13` for Operator 0.26.0 in `kustomization.yaml`, since the default PostgreSQL version has been updated from 12 to 13.

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx
...
secretGenerator:
  ...
  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres-13     👈👈👈
      - port=5432
      ...
```

If you have not modified this value, then it is expected that AWX will fail to connect to PostgreSQL and be in `Waiting for database migrations` since `awx-postgres` isn't there anymore.

I'll update my guide.
