### ISSUE TITLE
wrong secret configuration in Kustomization.yaml

### ISSUE THREAD

**Issue by stanislaspiron** [kurokobo/awx-on-k3s#114]
## Environment

- OS: CentOS Stream 8
- Kubernetes/K3s: v1.24.3+k3s1
- AWX Operator: 0.25

## Description

Same as https://github.com/kurokobo/awx-on-k3s/issues/113

I tried to deploy with Alpine and Centos with always the same issue... 
in postgre logs, I got this error:
```
ERROR:  relation "django_migrations" does not exist at character 124
```
## Solution

Remove type Opaque from kustomization.yaml file
```
  - name: awx-postgres-configuration
    type: Opaque   👈👈👈
    literals:
      - host=awx-postgres
      - port=5432
      - database=awx
      - username=awx
      - password=Ansible123!    
      - type=managed

  - name: awx-admin-password
    type: Opaque      👈👈👈
    literals:
      - password=Ansible123! 
```

Reason: Type Opaque means content is base64 encoded which is not in the example
