### ISSUE TITLE
Restore fails 

### ISSUE THREAD

**Issue by nicolaibaralmueller** [kurokobo/awx-on-k3s#14]
## Environment

- OS: CentOS 8
- Kubernetes/K3s: v1.21.5+k3s2
- AWX Operator: 0.14.0

## Description

Attempting to restore awx from another 0.14.0 awx installation. The folder was copied.

Restore fails with message `/data/backup/tower-openshift-backup-2021-10-19 does not exist, see the backupDirectory status on your AWXBackup for the correct backup_dir.`

## Step to Reproduce

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: awxrestore-2021-10-20
  namespace: awx
spec:
  # Parameters to restore from existing files on PVC (without AWXBackup object)
  backup_pvc_namespace: awx
  backup_pvc: awx-backup-claim
  backup_dir: /data/backup/tower-openshift-backup-2021-10-19
```

The backup exists in `/data/backup/tower-openshift-backup-2021-10-19`

First attempt resulted in the message that awx-backup-claim did not exist. So I executed `kubectl apply -f backup/awxbackup.yml` in order to create awx-backup-claim. 

For some reason AWX can't see the folder `/data/backup/tower-openshift-backup-2021-10-19` which puzzles me?

BR
