### ISSUE TITLE
How to reverse-proxy Ansible out to the internet with NGINX

### ISSUE THREAD

**Issue by MnM001** [kurokobo/awx-on-k3s#180]
OS: Ubuntu 22.04
Kubernetes/K3s: v1.21.5
AWX Operator: 1.1.4

Description

HI - thank you for the guides. I have deployed my AWX environment following it.
I can access AWX via HTTS and it work fine.

My question is about reverse proxy.

I am using NGINX to reverse proxy services out to the internet.
However, regardless of what I try I can get Ansible to work. 

My setup is:

- internal Ansible URL (configured at install time in base/awx.yaml as per your guides) - ansible.internal,local
- external URL that NGIX proxies - ansible.external.com (an example not the real URL)

NGINX configured just like all the other entries I have and all are working fine, expect the Ansible one.

Browsing to ansible.external.com gives me 404 page not found
Browsing to  ansible.internal,local is OK

I note your comments in the guide:

Note that you have to access via hostname that you specified in base/awx.yaml, instead of IP address, since this guide uses Ingress. So you should configure your DNS or hosts file on your client where the browser is running.

I understand the issue but I have no idea how to fix it so I can reverse-proxy Ansible for external access.

I hope there is a way to modify the config to allow Ingress to IP address as well (maybe restricted to the NGINX IP address only)?

Or maybe you have some other ideas?

Many thanks.

**Comment by kurokobo** [comment]
@MnM001 
Hi, thanks for using my guide.
If it's okay for you to use HTTP instead of HTTPS for internal AWX access, `nodeport` is the one of the preferred way. In this case, TLS termination should be enabled on your Nginx.

- ansible.external.com (HTTPS) -> Your Nginx (with TLS termination for HTTPS access) -> <Node IP Address>:30080 (HTTP) -> AWX

To achieve this, modify `base/awx.yaml` as follows;

```yaml
...
spec:
  # Comment following lines out
  # ingress_type: ingress
  # ingress_tls_secret: awx-secret-tls
  # hostname: awx.example.com

  # Add following lines
  service_type: nodeport
  nodeport_port: 30080  # You can modify port number in range 30000-32768

  ...
```

Then apply this and wait for AWX to be re-deployed;

```bash
kubectl apply -k base
```

Your AWX will be available as `http://<Node IP Address>:30080` and you can specify this as `proxy_pass` in your Nginx.

I recommend this approach because Ingress is a reverse proxy with TLS termination, and placing this behind Nginx to it simply adds more overhead.
