### ISSUE TITLE
Can not mount a ssh-key in the Pod

### ISSUE THREAD

**Issue by David-yanp** [kurokobo/awx-on-k3s#181]
## Environment

- OS: Ubuntu 20.04.5 LTS
- Kubernetes/K3s: v1.25.3+k3s1 (f2585c16)
- AWX Operator: 0.29.0

## Description
I am following the [documents](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/use-kerberos.md) to mount a ssh key in my pod so that the pod can connect to a bastion host, but it is not working. Not even mounting a file is successful.

## Step to Reproduce

1. I created a file named abc5.conf using the following command: kubectl -n awx create configmap awx-kerberos-config --from-file=abc5.conf
```bash
cat abc5.conf 
[realms]
  KUROKOBO.INTERNAL = {
    kdc = kuro-ad01.kurokobo.internal
    admin_server = kuro-ad01.kurokobo.internal
  }

[domain_realm]
  .kurokobo.internal = KUROKOBO.INTERNAL
  kurokobo.internal = KUROKOBO.INTERNAL
```
2. I added volumes to the Instance Groups as follows:
```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  containers:
    - image: quay.io/davidyp/pylibssh:latest
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      resources:
        requests:
          cpu: 250m
          memory: 100Mi
      volumeMounts:
        - name: shared-volume
          mountPath: /shared
        - name: awx-kerberos-volume
          mountPath: /etc/abc5.conf
          subPath: abc5.conf
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: awx-files-claim
    - name: awx-kerberos-volume
      configMap:
        name: awx-kerberos-config
  securityContext:
    runAsUser: 1000
```
3. I used `kubectl -n awx describe pod` to list the volumes, but the `awx-kerberos-volume` was not shown.

Did I miss something or should I use another method to achieve this? Any advice would be appreciated.

**Comment by kurokobo** [comment]
@David-yanp 
Hi, thanks for using my guide.
In the first place, why did you follow that guide to mount SSH key? That guide is not to mount SSH key on the pod but to use Kerberos authentication. `abc5.conf` is not SSH key. `/etc/abc5.conf` is not a path for SSH key.

Could you be more specific about your goal?

**Comment by David-yanp** [comment]
@kurokobo 
Hi, thank you for your reply.
Yes, I know this guide is not for ssh-key, I can't find a proper way to do this. So I tried to mount a file on the Pod, but that didn't work either.
I have been tried to using the secret to mount an ssh-key and it's not working. 
I don't know how to do this,could you guide me how can I mount an SSH key or a batch of SSH key in the Pod?

**Comment by kurokobo** [comment]
@David-yanp 
If you simply want to connect to the target node of the playbook via SSH with public key authentication, you can add the SSH key to your credentials.

![image](https://user-images.githubusercontent.com/2920259/218637082-a779c84d-502c-44a0-8adb-5622c55b8ac6.png)

Rather, do you want to connect to the target node via bastion host? If so, you may want to use Container Group as you have tried.

The pod spec in the Container Group is the spec for ephemeral automation job pod which is created on job launch and removed after job completion. I think your configuration is correct, but if you invoke `describe pod` when no job is running, you can see nothing. You should invoke `describe pod` during job runtime.

Ensure that your Container Group is specified in Job Template. Also for SSH key, you sould consider permission for the file to be mounted.

```yaml
  volumes:
    ...
    - name: awx-kerberos-volume
      configMap:
        name: awx-kerberos-config
        items:
          - key: your-file
            path: your-file
            mode: 0600
```

In addition, this is a bit different approach, there is a good feature called Execution Node in AWX. Plrobably you can replace your bastion host with it without any SSH key.

https://github.com/ansible/awx/blob/devel/docs/execution_nodes.md

**Comment by kurokobo** [comment]
Also I recommend you to ask this on official mailing list or IRC channel. This is a good use case of AWX.
https://github.com/ansible/awx#get-involved

**Comment by David-yanp** [comment]
Thanks for the suggestion, I see Execution Node is a way to select nodes in a cluster without needing ssh-keys, but my bastion 
 host and current AWX are in different locations so it's not ideal for this solution. 
Could you spare a bit more time to help me see if my steps for mounting the ssh-key on a Pod are correct? 
1. `kubectl -n awx create configmap awx-ssh-keys --from-file=id_rsa`
2.  `kubectl -n awx get configmap`
```
NAME                              DATA   AGE
kube-root-ca.crt                  1      89d
awx-operator-awx-manager-config   1      89d
awx-awx-configmap                 5      89d
awx-ssh-keys                      1      54m
awx-operator                      0      89d
```
3. Custom pod spec under Instance Groups 
```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  containers:
    - image: quay.io/davidyp/pylibssh:latest
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      resources:
        requests:
          cpu: 250m
          memory: 100Mi
      volumeMounts:
        - name: shared-volume
          mountPath: /shared
        - name: awx-ssh-volume
          mountPath: /root/.ssh
          subPath: id_rsa
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: awx-files-claim
    - name: awx-ssh-volume
      configMap:
        name: awx-ssh-keys
  imagePullSecrets:
    - name: davidyp-pull-secret
  securityContext:
    runAsUser: 1000
```
5. running a job and get in the pod with `kubectl -n awx exec -it `kubectl -n awx get pods|tail -n 1| awk '{print $1}'` -- /bin/bash`
6.  Using `ls /root/.ssh/' to check the directory doesn't have the file.
Still can't find the Ssh-key in the Pod. Thanks.

**Comment by kurokobo** [comment]
@David-yanp 

>  I see Execution Node is a way to select nodes in a cluster without needing ssh-keys

Nop, Execution Node is a way to use any standalone linux nodes for job execution. The automation job container will run on Podman on Execution Node, without Kubernetes.

Anyway, not fully tested, but I can confirm my `id_rsa` can be mounted in the pod and can SSH to connect another host using the key.

1. Create kay pair

   ```bash
   ssh-keygen -t rsa -f ./id_rsa
   ```

1. Copy public key to jump host

   ```bash
   ssh-copy-id -i ./id_rsa demo@jumphost
   ```

1. Create Secret from generated `id_rsa`

   ```bash
   kubectl -n awx create secret generic awx-ssh-key --from-file=./id_rsa
   ```

1. Ensure `awx-ssh-key` is created

   ```bash
   $ kubectl -n awx describe secret awx-ssh-key
   Name:         awx-ssh-key
   Namespace:    awx
   Labels:       <none>
   Annotations:  <none>
   
   Type:  Opaque
   
   Data
   ====
   id_rsa:  2610 bytes
   ```

1. Create new Container Group on AWX with following pod spec

   ```yaml
   apiVersion: v1
   kind: Pod
   metadata:
     namespace: awx
   spec:
     serviceAccountName: default
     automountServiceAccountToken: false
     containers:
       - image: 'quay.io/ansible/awx-ee:latest'
         name: worker
         args:
           - ansible-runner
           - worker
           - '--private-data-dir=/runner'
         resources:
           requests:
             cpu: 250m
             memory: 100Mi
         volumeMounts:
           - name: awx-ssh-volume
             mountPath: /home/runner/.ssh
     volumes:
       - name: awx-ssh-volume
         secret:
           secretName: awx-ssh-key
   ```

1. Modify Job Template to use Container Group ([Templates] > [Edit] > [Instance Groups])

1. Launch Job Template

1. Dig into the newly created Automation Job Pod

   ```bash
   # Get Bash session of the pod
   $ kubectl -n awx exec -it $(kubectl -n awx get pod -o=name | grep automation-job) -- bash
   
   # Ensyre the key is mounted
   $ kubectl -n awx describe $(kubectl -n awx get pod -o=name | grep automation-job)
   ...
   Containers:
     worker:
       ...
       Mounts:
         /home/runner/.ssh from awx-ssh-volume (rw)
       ...
   Volumes:
     awx-ssh-volume:
       Type:        Secret (a volume populated by a Secret)
       SecretName:  awx-ssh-key
       ...

   # Ensure the key is visible in the pod
   $ ls -l /home/runner/.ssh/id_rsa 
   lrwxrwxrwx. 1 root root 13 Feb 14 16:35 /home/runner/.ssh/id_rsa -> ..data/id_rsa
   
   # Ensure connecting the jump host via SSH using the key works as expected
   bash-5.1$ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null demo@jumphost
   Warning: Permanently added 'jumphost' (ED25519) to the list of known hosts.
   Last login: Wed Feb 15 01:19:24 2023 from 10.42.0.31
   [demo@jumphost ~]$
   ```
