### ISSUE TITLE
how to Customize logo

### ISSUE THREAD

**Issue by chaitanya486** [kurokobo/awx-on-k3s#188]
## Environment

- OS: CentOS X.Y, RHEL X.Y, Ubuntu X.Y, Debian X.Y, ...
- Kubernetes/K3s: X.Y.Z
- AWX Operator: X.Y.Z

## Description

Blah blah blah ...

## Step to Reproduce

1. Deploy ...
2. Invoke `kubectl ...`
3. ...
4. ...

## Logs

```bash
$ kubectl ...
...
```

## Files

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
...
```
