### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by SorenSj** [kurokobo/awx-on-k3s#24]
## Environment
k3s version: v1.22.5+k3s1 (405bf79d)

- OS: Rocky Linux 8.5
- AWX Operator: 0.15.0

## Description
The installation and configuration of awx goes immediately well. There are no error messages.
But when I try to access awx via my ip address (http://10.10.0.9) the error message comes: "404 page not found". The same goes for access via https.
What am I missing?

**Comment by kurokobo** [comment]
Access AWX via hostname instead of IP address. Kubernetes routes your HTTP trafic according to the `HOST` header in the HTTP request.

Therefore, if you specify `awx.example.com` as described in my repo,

```yaml
...
spec:
  ...
  ingress_type: ingress
  ingress_tls_secret: awx-secret-tls
  hostname: awx.example.com     👈👈👈
...
```

your AWX can be accessed via `https://awx.example.com` instead of IP address. So you should configure your DNS or `hosts` file on your client (where the brower is running).
