### ISSUE TITLE
Restoring just gives 404 page not found?

### ISSUE THREAD

**Issue by toutas** [kurokobo/awx-on-k3s#257]
## Environment
k3s version v1.27.4+k3s1 (36645e73)
go version go1.20.6

- OS: Ubuntu 20.04.6 LTS
- AWX Operator: 2.5.1

## Description
I read the tips/troubleshooting.md and found no logs or anything that seemed suspicious or relevant.

My issue is I am trying to restore from a backup created using the /2.5.1//backup/README.md and /2.5.1/restore/README.md walkthroughs

I have been able to successfully backup and restore on 0.30.0, but since having made a clean 2.5.1 install, and having decided now is the time for backup and restore testing, I have not been able to get it to work again.

## Step to Reproduce

1. I set up my initial vm using the walkthrough in /2.5.1/README.md. I included /2.5.1/acme#readme since I have a cloudflare account.

**my acme/issuer.yaml:**
```
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: awx-issuer
spec:
  acme:
    # The email address to be registered with ACME CA
    email: <email>

    # The URL of the ACME API endpoint.
    # In Let's Encrypt, this is one of the following:
    #   Production: https://acme-v02.api.letsencrypt.org/directory
    #   Staging   : https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: awx-issuer-account-key

    solvers:
      - dns01:
          cloudflare:
            email: <email
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

```

**my acme/kustomization.yaml:**
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloudflare-api-token-secret
    type: Opaque
    literals:
      - api-token=<cloudflareapitoken>

resources:
  - issuer.yaml

```

**My base/awx.yaml:**

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  admin_user: admin
  admin_password_secret: awx-admin-password

  ingress_type: ingress
  ingress_tls_secret: awx-secret-tls
  hostname: <awx.hostname.site>

  ingress_annotations: |
    cert-manager.io/issuer: awx-issuer
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd

  postgres_configuration_secret: awx-postgres-configuration

  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 8Gi

  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  web_replicas: 1
  task_replicas: 1

  postgres_init_container_resource_requirements: {}
  postgres_resource_requirements: {}
  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}
  init_container_resource_requirements: {}

  # Uncomment to reveal "censored" logs
  #no_log: false
```

**My base/kustomization.yaml:**

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres-13
      - port=5432
      - database=awx
      - username=awx
      - password=<awx_pg_pw>
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=<awx_admin_pw>

resources:
  - pv.yaml
  - pvc.yaml
  - awx.yaml

```

2. I then created a **backup/awxbackup.yaml**:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awx-backup-20230906210105
  namespace: awx
spec:
  deployment_name: awx
  backup_pvc: awx-backup-claim

  # Uncomment to reveal "censored" logs
  #no_log: "false"

```
and went through the steps to get the backup folder, tar.gz it and upload it to my storage.

3. I then setup a new VM for restoring. I performed all the steps as in 1. except the `kubectl apply -k base`´. I have an ansible playbook with all of this if that would help, as I am automating everything.

4. I then prepare for restore:

```
        - sudo mkdir -p /data/backup
        - sudo chmod 755 /data/backup
        - mv backup.tar.gz /data/backup/
        - tar -xzf /data/backup/backup.tar.gz -C /data/backup
        - kubectl apply -k restore
        - update restore/awxrestore.yaml with name of backup folder

---
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: awxrestore-2023-09-06
  namespace: awx
spec:
  deployment_name: awx

  # Parameters to restore from AWXBackup object
  #backup_name: awxbackup-2021-06-06

  # Parameters to restore from existing files on PVC (without AWXBackup object)
  backup_pvc: awx-backup-claim
  backup_dir: /backups/tower-openshift-backup-2023-09-06-210119

  # Uncomment to reveal "censored" logs
  #no_log: false
```

I then apply restore with kubectl apply -f ~/awx-on-k3s/restore/awxrestore.yaml, and it runs successfully and ends without any failures. see image. 
![image](https://github.com/kurokobo/awx-on-k3s/assets/61290992/3aa93d2a-1a2f-4345-af47-894bc9c73976)
   
5. I update my cloudflare A record that points my awx.my.domain to the new VM, ensuring vm has port 80 and 443 open, and when I confirm in chrome that the domain I am reaching has the IP that my new vm has, I see 404 page not found. Chrome does not cry about missing cert, so that was sent successfully by traefik.

## Logs
I got not error messages, and no logs show failures, EXCEPT kubectl -n awx logs -f deployment/awx-task -c awx-task:

![image](https://github.com/kurokobo/awx-on-k3s/assets/61290992/151c00af-796c-4a79-b6db-ce4daaddab52)

again this did not seem relevant to me. 

When I run kubectl -n awx get awx,all,ingress,secrets I get

![image](https://github.com/kurokobo/awx-on-k3s/assets/61290992/77417a09-5f4d-45f4-8557-7370415cc426)

I do not see any issues here whatsoever as well, and I did check the logs as requested in tips/troubleshooting.md

Hope you are able to help me figure out where I went wrong!
