### ISSUE TITLE
How can I deploy a awx-on-k3s on many nodes

### ISSUE THREAD

**Issue by cxlll1234** [kurokobo/awx-on-k3s#380]
## Environment

- OS: Oracle Linux8
- Kubernetes/K3s: K3S v1.26.5+k3s1
- AWX Operator: 24.5.0

## Description

I want to deploy awx-on-k3s on many nodes.
But I don't know how to deploy it

## Step to Reproduce

1. Deploy ...
2. Invoke `kubectl ...`
3. ...
4. ...

## Logs

```bash
$ kubectl ...
...
```

## Files

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
...
```
