### ISSUE TITLE
Execution environment marked as latest is not actually latest after update

### ISSUE THREAD

**Issue by amg-web** [kurokobo/awx-on-k3s#387]
## Environment
OS: Ubuntu 22.04
Kubernetes/K3s: v1.30.4+k3s1
AWX Operator: 2.19.1

## Description
Execution environment marked as **latest** is not actually latest after update of AWX from older versions.
![Screenshot from 2024-08-31 11-43-06](https://github.com/user-attachments/assets/d8d86175-7644-4471-a445-05a0f121ecc1)
I understood this when route53 module failed with error message
> "msg": "Failed to import the required Python library (botocore and boto3) on automation-job-434-lfn5s's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"

Then I switched template to use specific version EE and all jobs were done.

with minikube I used this in kustomization.yaml, did not checked yet if it works.
```
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.12.1
  - name: quay.io/ansible/awx-ee
    newTag: latest
```
