### ISSUE TITLE
AWX portal not accessible

### ISSUE THREAD

**Issue by compuserv2017** [kurokobo/awx-on-k3s#398]
## Environment

- OS: Ubuntu 24.04.1 LTS
- Kubernetes/K3s: K3s v1.29.6+k3s2
- AWX Operator 2.19.1

## Description
everything seems to be running fine. however, after the installation is completed, I can't seem to access the web interface
(whenever i put in the IP, it just gives me: 404 page not found)

![sad](https://github.com/user-attachments/assets/1027751c-70e5-474f-bb74-cad5ce052e16)

all pods seem to be up and healthy.

![pods](https://github.com/user-attachments/assets/02dd321e-86ee-4746-80ce-7cf623819133)

## Step to Reproduce

1. Deploy following the guide on Ubuntu 24.04.1 LTS (UFW dissabled as suggested)
2. try to visit the web page after finishing up

## Logs
there don't seem to be any unhealthy pods/logs

## Files

awx.yaml:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  # These parameters are designed for use with:
  # - AWX Operator: 2.19.1
  #   https://github.com/ansible/awx-operator/blob/2.19.1/README.md

  admin_user: admin
  admin_password_secret: awx-admin-password

  ingress_type: ingress
  ingress_hosts:
    - hostname: ansible.test.local
      tls_secret: awx-secret-tls

  postgres_configuration_secret: awx-postgres-configuration

  postgres_data_volume_init: true
  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 8Gi

  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  web_replicas: 1
  task_replicas: 1

  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}
  init_container_resource_requirements: {}
  postgres_resource_requirements: {}
  redis_resource_requirements: {}
  rsyslog_resource_requirements: {}

  # Uncomment to reveal "censored" logs
  #no_log: false
```

kustomization.yaml

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres-15
      - port=5432
      - database=awx
      - username=awx
      - password=Ansible123!
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=Ansible123!

  # If you want to specify SECRET_KEY for your AWX manually, uncomment following lines and change the value.
  # Refer AAC documentation for detail about SECRET_KEY.
  # https://docs.ansible.com/automation-controller/latest/html/administration/secret_handling.html
  #- name: awx-secret-key
  #  type: Opaque
  #  literals:
  #    - secret_key=MySuperSecureSecretKey123!

resources:
  - pv.yaml
  - pvc.yaml
  - awx.yaml
```
