### ISSUE TITLE
Google announcement of retiring `gcr.io` registry and would cause problem k3s build

### ISSUE THREAD

**Issue by kazichaska** [kurokobo/awx-on-k3s#404]
## Environment

- OS: Ubuntu 22
- Kubernetes/K3s: v1.28.8+k3s1
- AWX Operator: 2.0.0

## Description
Sorry if this is already taken care of, Google announcement of retiring gcr.io registry https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown and would cause issue for k3s build as one docker image is in use for this version. 

gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0 

How would I point it to something to get this working going forward?

## Step to Reproduce
It is on the AWX k3s just grepping docker images -a | grep gcr would show

**Comment by kurokobo** [comment]
@kazichaska 
Hi, thanks for the confirmation.

Yes, I know about the retiring GCR, and it's true that the image `kube-rbac-proxy` will be affected.
However, in the first place, the `kube-rbac-proxy` has been discontinued in Kubebuilder, so Red Hat should make a decision on how to handle both the discontinued `kube-rbac-proxy` and the retiring GCR. Refar to: https://github.com/kubernetes-sigs/kubebuilder/discussions/3907

Anyway, technically, there is a workaround; we can replace it with `quay.io/brancz/kube-rbac-proxy` or `bitnami/kube-rbac-proxy` by customizing `operator/kustomization.yaml`.

Due to the recent extensive modifications of AWX, the release has been temporarily paused, and I have also temporarily halted updates to this repository. However, while monitoring the developments on the AWX Operator side, I intend to update `operator/kustomization.yaml` in this repository if necessary.

**Comment by kazichaska** [comment]
@kurokobo thanks much for quick response and all the information. Can you please confirm this so I understand what needs to be done. You are saying use kustomization.yaml file and change the gcr.io image path with one of these quay.io/brancz/kube-rbac-proxy or bitnami/kube-rbac-proxy. If you do not mind adding a sample example would really be appreciated. TIA.

**Comment by kurokobo** [comment]
Not tested, but updated `operator/kustomization.yaml` may be something like this:

For Operator 2.0.0:

```yaml
...
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.0.0
  - name: gcr.io/kubebuilder/kube-rbac-proxy
    newName: quay.io/brancz/kube-rbac-proxy
    newTag: v0.13.0
```

For Operator 2.19.1 (latest):

```yaml
...
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1
  - name: gcr.io/kubebuilder/kube-rbac-proxy
    newName: quay.io/brancz/kube-rbac-proxy
    newTag: v0.15.0
```

**Comment by kazichaska** [comment]
Thanks much @kurokobo I will give this ^ and try and see if my VM builds without issue :-) Again appreciate it!

**Comment by kazichaska** [comment]
@kurokobo I have tried build my server using https://github.com/ansible/awx-operator/releases/tag/2.18.0 version and it built fine but again used `gcr.io v0.15.0`  https://console.cloud.google.com/artifacts/docker/kubebuilder/us/gcr.io/kube-rbac-proxy/sha256:d8cc6ffb98190e8dd403bfe67ddcb454e6127d32b87acc237b3e5240f70a20fb;tab=install 

Do you know if https://github.com/ansible/awx-operator/releases would include the other repository you mentioned above or any other stable/secure/safe image? Instead of feeding using my `kustomization.yaml`; the actual source is updated with proper version. Since Google would not have this I am guessing lot of people are going to be having same issue as me :-) 

BTW I tried with Redhat version https://catalog.redhat.com/software/containers/rhacm2/kube-rbac-proxy-rhel8/611d4320eb34b73652492bb8 and it does not work.

**Comment by kurokobo** [comment]
I can confirm that appending following three lines into `operator/kustomization.yaml` and deploying operator again by `kubectl apply -k operator` changes the `kube-rbac-proxy` to use `quay.io/brancz/kube-rbac-proxy:v0.15.0` as expected:

```yaml
  - name: gcr.io/kubebuilder/kube-rbac-proxy
    newName: quay.io/brancz/kube-rbac-proxy
    newTag: v0.15.0
```

> Do you know if https://github.com/ansible/awx-operator/releases would include the other repository you mentioned above or any other stable/secure/safe image?

Typical AWX deployment uses followig images:

```bash
$ kubectl -n awx describe pod | grep Image: | sed 's/\s\+/ /g' | sort | uniq
 Image: docker.io/redis:7
 Image: quay.io/ansible/awx:24.6.1
 Image: quay.io/ansible/awx-ee:24.6.1
 Image: quay.io/ansible/awx-operator:2.19.1
 Image: quay.io/brancz/kube-rbac-proxy:v0.15.0
 Image: quay.io/centos/centos:stream9
 Image: quay.io/sclorg/postgresql-15-c9s:latest
```

I do not assert whether this is stable, secure, or safe.

It is Red Hat that decides on the images to adopt, and it was also Red Hat that made the decision to suspend the releases of AWX and AWX Operator for a while.

Whether you consider it acceptable to use images built seven months ago is your responsibility and decision, not mine.
