### ISSUE TITLE
Restore seems to fail

### ISSUE THREAD

**Issue by nicolaibaralmueller** [kurokobo/awx-on-k3s#5]
## Environment

- OS: Centos 8.3
- Kubernetes/K3s: 1.21.3
- AWX Operator: 0.13.0

## Description

Hi,

Did a test backup which was executed as expected. The backup data exists. However, restore was not successful. 

Not sure which part to pick out from the log but here is an example. 

```
TASK [Create management pod from templated deployment config] ******************************** 
fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Pod \\\\\"awxrestore-2021-08-30-db-management\\\\\" is invalid: [spec.volumes[0].persistentVolumeClaim.claimName: Required value, spec.containers[0].volumeMounts[0].name: Not found: \\\\\"awxrestore-2021-08-30-backup\\\\\"]\",\"reason\":\"Invalid\",\"details\":{\"name\":\"awxrestore-2021-08-30-db-management\",\"kind\":\"Pod\",\"causes\":[{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"spec.volumes[0].persistentVolumeClaim.claimName\"},{\"reason\":\"FieldValueNotFound\",\"message\":\"Not found: \\\\\"awxrestore-2021-08-30-backup\\\\\"\",\"field\":\"spec.containers[0].volumeMounts[0].name\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}
```

Did I miss something? 

Thanks

**Comment by kurokobo** [comment]
@nicolaibaralmueller 
Thanks for reporting, seems something wrong with the value `backup_pvc` in your `awxrestore.yml` I think.
This should be the name of PVC (i.e. `awx-backup-claim`) instead of the name of the AWXBackup (i.e. `awxbackup-2021-06-06`).

- Can you share your `awxrestore.yml` ?
- To correct your `awxrestore.yml`, can you paste the output from following commands?
  - `kubectl get pv`
  - `kubectl -n awx get pvc`
  - `kubectl -n awx get awxbackup`
  - `kubectl -n awx get awxbackup -o jsonpath="{.items[].status.backupClaim}"`
  - `ls -l /data/backup` (change path to suit your PV)

**Comment by nicolaibaralmueller** [comment]
@kurokobo 

Not sure what is going on here.

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: awxrestore-2021-09-01
  namespace: awx
spec:
  deployment_name: awx
  # Parameters to restore from AWXBackup object
  backup_pvc_namespace: awx-backup-claim
  backup_name: awxbackup-2021-08-30

  # Parameters to restore from existing files on PVC (without AWXBackup object)
  #backup_pvc_namespace: awx
  #backup_pvc: awx-backup-claim
  #backup_dir: /backups/tower-openshift-backup-2021-06-06-10:51:49
```

```
[root@awx2 ~]# k3s kubectl get pv
NAME                  CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                         STORAGECLASS          REASON   AGE
awx-projects-volume   2Gi        RWO            Retain           Bound    awx/awx-projects-claim        awx-projects-volume            37h
awx-postgres-volume   2Gi        RWO            Retain           Bound    awx/postgres-awx-postgres-0   awx-postgres-volume            37h
awx-backup-volume     2Gi        RWO            Retain           Bound    awx/awx-backup-claim          awx-backup-volume              37h
[root@awx2 ~]# k3s kubectl -n awx get pvc
NAME                      STATUS   VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS          AGE
awx-projects-claim        Bound    awx-projects-volume   2Gi        RWO            awx-projects-volume   37h
postgres-awx-postgres-0   Bound    awx-postgres-volume   2Gi        RWO            awx-postgres-volume   37h
awx-backup-claim          Bound    awx-backup-volume     2Gi        RWO            awx-backup-volume     37h
[root@awx2 ~]# k3s kubectl -n awx get awxbackup
NAME                   AGE
awxbackup-2021-08-30   37h
[root@awx2 ~]# k3s kubectl -n awx get awxbackup -o jsonpath="{.items[].status.backupClaim}"
awx-backup-claim[root@awx2 ~]# 
[root@awx2 ~]# ls -l /data/backup
total 0
drwxr-xr-x. 2 root root 59 Aug 30 20:02 tower-openshift-backup-2021-08-30-18:02:12
```

`
--------------------------- Ansible Task Status Event StdOut  -----------------

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


-------------------------------------------------------------------------------
{"level":"error","ts":1630483414.3761735,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awxrestore-controller","request":"awx/awxrestore-2021-09-01","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}

`

**Comment by kurokobo** [comment]
@nicolaibaralmueller 
Thanks for updating!

I found a wrong value in your `awxrestore.yml`.
`backup_pvc_namespace` have to be the name of `namespace` which the PVC exists. I mean, in your environment, this value have to have `awx` instead of `awx-backup-claim`.

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: awxrestore-2021-09-01
  namespace: awx
spec:
  deployment_name: awx
  # Parameters to restore from AWXBackup object
  backup_pvc_namespace: awx-backup-claim     👈👈👈 This have to be "awx"
  backup_name: awxbackup-2021-08-30
```

Please fix this and retry. Other than this, everything else seems to be fine.
