### ISSUE TITLE
AWX and community module installation

### ISSUE THREAD

**Issue by nicolaibaralmueller** [kurokobo/awx-on-k3s#6]
## Environment

- OS: CentOS 8
- Kubernetes/K3s: 1.21.3
- AWX Operator: 0.13.0

## Description

Hi,

I am having issues figuring out how to install community module requirements and notices that you code contains builder/requirements.yml and builder/requirements.txt. 

Can these be used to customize which modules are present at runtime? 

Can't execute community.vmware modules since it's nowhere described how to do this in AWX.

## Step to Reproduce

```
- name: Make sure requirements are met to run vmware modules
  become: true
  ansible.builtin.pip:
    name: pyVmomi
    state: present

- name: Export virtual machine facts
  community.vmware.vmware_guest_info:
    hostname: "{{ hostname }}"
    username: '{{ domain_user }}'
    password: "{{ domain_password }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    schema: vsphere
    name: VM01
  register: virtualmachine_facts
```

Both commands result in:

```
fatal: [127.0.0.1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "module_stderr": "/bin/sh: sudo: command not found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 127
}
```
