### ISSUE TITLE
AWX Restore question

### ISSUE THREAD

**Issue by nicolaibaralmueller** [kurokobo/awx-on-k3s#71]
Hi,

Upgraded 14.0.0 to 21.0.0 and sure enough there is a bug... again. Downgrading resultet in an unknown AWX error so now I have to restore for the first time.

I've deleted everything and have the backup folder here: `/data/restore/tower-openshift-backup-2022-05-05-02:01:07`

No backup deployment present. Just the files.

Next step: `kubectl apply -k restore`

Now I am unsure how `restore/awxrestore.yaml` should look. Is this correct? Should a base awx be installed first before restoring the pvc? 

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: awxrestore-2022-05-05
  namespace: awx
spec:
  deployment_name: awx

  # Parameters to restore from AWXBackup object
  #backup_pvc_namespace: awx
  #backup_name: awxbackup-2021-06-06

  # Parameters to restore from existing files on PVC (without AWXBackup object)
  backup_pvc_namespace: awx
  backup_pvc: awx-backup-claim
  backup_dir: /backups/tower-openshift-backup-2022-05-05-02:01:07
```
