### ISSUE TITLE
Can I add an existing PostgreSQL database dump file to the deployment?

### ISSUE THREAD

**Issue by jheinitz** [kurokobo/awx-on-k3s#76]
Hello!

I like your straight forward approach to deploy AWX on Kubernetes. We have currently a setup where we deployed AWX 19 on Docker and therefore have an existing environment. Would it be possible to load a PostgreSQL database dump file instead of starting with a fresh install?

Thanks in advance and best regards

Jens

**Comment by kurokobo** [comment]
Hi, thanks for taking an interest in my repo :)

> Would it be possible to load a PostgreSQL database dump file instead of starting with a fresh install?

There is an official way to migrate data from old AWX instance. You should follow the instructions on [migration.md](https://github.com/ansible/awx-operator/blob/devel/docs/migration.md) in the AWX Operator's repo.

**Comment by jheinitz** [comment]
Hello @kurokobo !
Thanks for the tip. That worked fine for us. I followed the migration guide, but added the additional secrets to the kustomization.yaml in the base folder like this:

```
  - name: awx-secret-key
    type: Opaque
    literals:
      - secret_key=my_dummy_key
```
and
```
  - name: awx-old-postgres-configuration
    type: Opaque
    literals:
      - host=ansible03.example.de
      - port=5432
      - database=awx
      - username=awx
      - password=awxpass
      - type=managed
```
Finally I added these lines to the awy.yaml in the base folder:
```
  #
  # Add PostgreSQL configuration where the old AWX 19.x database dump is loaded
  #
  old_postgres_configuration_secret: awx-old-postgres-configuration
  #
  # Specify the secret_key which was used in the old AWX 19.x deployment
  #
  secret_key_secret: awx-secret-key
```
Thanks for your help!

Best regards

Jens

**Comment by jheinitz** [comment]
Hello @everydaylearner 
Sure! Here you go.
`kustomization.yaml:`
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-custom-certs
    type: Opaque
    files:
      - ldap-ca.crt=cacert.pem
      - bundle-ca.crt=cacert.pem

  - name: awx-old-postgres-configuration
    type: Opaque
    literals:
      - host=postgres.example.com
      - port=5432
      - database=awx
      - username=awx
      - password=<passwd-for-awx>
      - type=managed

  - name: awx-secret-key
    type: Opaque
    literals:
      - secret_key=<secret from old AWX 19 installation>

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres
      - port=5432
      - database=awx
      - username=awx
      - password=awxpass
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=<my-admin-passwd>

  # Temporary workaround to suppress errors from AWX Operator 0.21.0.
  # Refer: https://github.com/kurokobo/awx-on-k3s/issues/74
  - name: redhat-operators-pull-secret
    files:
      - .dockerconfigjson=dockerconfig.json
    type: kubernetes.io/dockerconfigjson

resources:
  - pv.yaml
  - pvc.yaml
  - awx.yaml
```
`awx.yml:`
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  # These parameters are designed for use with:
  # - AWX Operator: 0.21.0
  #   https://github.com/ansible/awx-operator/blob/0.21.0/README.md
  # - AWX: 21.0.0
  #   https://github.com/ansible/awx/blob/21.0.0/INSTALL.md

  #
  # Specify our Root CA (cacert.pem) for LDAP and Bundle ...
  #
  ldap_cacert_secret: awx-custom-certs
  bundle_cacert_secret: awx-custom-certs

  admin_user: admin
  admin_password_secret: awx-admin-password

  ingress_type: ingress
  ingress_tls_secret: awx-secret-tls
  hostname: ansible.example.com

  ingress_annotations: |
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd

  #
  # Add PostgreSQL configuration where the old AWX 19.x database dump is loaded
  #
  old_postgres_configuration_secret: awx-old-postgres-configuration

  #
  # Specify the secret_key which was used in the old AWX 19.x deployment
  #
  secret_key_secret: awx-secret-key

  postgres_configuration_secret: awx-postgres-configuration

  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 8Gi

  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}
```
For the PostgreSQL database from the old AWX installation, I created a temporary PostgreSQL instance where I placed a dump file in the /opt/postgresql/initdb.d directory. This is the PostgreSQL installation I'm referencing as postgres.example.com above.

`docker-compose.yml`:
```
--
services:
  postgres:
    container_name: postgres_1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: awx
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: awxpass
      POSTGRES_USER: awx
    image: postgres:12
    restart: unless-stopped
    volumes:
      - /opt/postgresql/initdb.d:/docker-entrypoint-initdb.d:ro
      - /opt/postgresql/data:/var/lib/postgresql/data:rw
...
```

Hopefully this works for you. 

Best regards

Jens
