### ISSUE TITLE
CERT & Admin password - NOT WORKING

### ISSUE THREAD

**Issue by rajspeed1** [kurokobo/awx-on-k3s#78]
## Environment

- OS: CentOS X.Y, RHEL X.Y, Ubuntu X.Y, Debian X.Y, ...
- Kubernetes/K3s: 1.23.6
- AWX Operator: 0.21.0

## Description

I've modified awx password under  awx.yaml & deployed with my own Custom Certs.
However, post deployment SSL is not enabled & even modified password is not working.  
In kubectl secret | base 64, I can see the password is updated with specified one.

But when changed the admin password through awx-manage (inside pod) it worked.

Can you pls. retest if both SSL & Custom password is working.

**Comment by kurokobo** [comment]
@rajspeed1 
Hi, thanks for using my guide.
Of course I've tested with custom certificate and custom password and works well on my side.

- Could you please provide your `kustomization.yaml` and `awx.yaml`?
- Ensure your cert file and key file have PEM format correctly.

AWX Operator will not update the password if the admin user already exists in the DB. If you have redeployed AWX multiple times, there is possibility that the admin user was remained in the old DB and AWX Operator had not updated the password.

**Comment by jheinitz** [comment]
Hello @rajspeed1 

just a few days ago, I deployed AWX 0.21.0 on K3S using this Repo. The deployment of custom certs went well. I had to name the files exactly "tls.crt" and "tls.key". 
Regarding the admin password, I think that this is only considered when you deploy a fresh installation. As soon as you follow the migration path, the old admin password is still valid.

Hope that it helps you.

Kind regards

Jens

**Comment by rajspeed1** [comment]
Hi @jheinitz 

Thanks for confirming. 
Reg admin password : Yes, I made second time deployment - so this is clear, why it didnt updated the password.
But coming to SSL cert, I copied as tls.crt and tls.key, but still it starts on port 80 with no ssl cert
Below is my kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres
      - port=5432
      - database=awx
      - username=awx
      - password=Ans@dm1n
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=Ans@dm1n

  # Temporary workaround to suppress errors from AWX Operator 0.21.0.
  # Refer: https://github.com/kurokobo/awx-on-k3s/issues/74
  - name: redhat-operators-pull-secret
    files:
      - .dockerconfigjson=dockerconfig.json
    type: kubernetes.io/dockerconfigjson

resources:
  - pv.yaml
  - pvc.yaml
  - awx.yaml

**Comment by jheinitz** [comment]
Hi again,

does it only listen on port 80/tcp or also on 443/tcp. If I got it right, you need to follow the [http-to-https redirect tip](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/https-redirection.md) in order to redirect traffic on port 80 to port 443.

Kind regards

Jens

**Comment by kurokobo** [comment]
@jheinitz 
Thanks for the comment! It helped me since I was away from my PC :)

@rajspeed1
I agree with @jheinitz 's comment. Could you please check that the 443 is works or not ?
In addition this is just F.Y.I., but you can wrap your YAML with triple back-quotes (` ``` `)to contain YAML strings into the comment with easy-to-read format.

If you wrap YAML strings with triple back-quotes like this:
````
```     👈👈👈
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key
```     👈👈👈
````

this will be rendered as:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key
```
