### ISSUE TITLE
How to specify an additional DNS Alias  beside hostname

### ISSUE THREAD

**Issue by jheinitz** [kurokobo/awx-on-k3s#86]
Hi, 

we have two servers where we deploy our AWX instance. They are called `ansible01.example.com` and `ansible02.example.com`. We create a DNS alias and issue the certificates with an additional SAN called `ansible.example.com`. 

In the `base/awx.yml` the hostname has to match the hostname of the URL that is later used to contact AWX. Otherwise you will get a 404 error. 
```
...
spec:
  ...
  ingress_type: ingress
  ingress_tls_secret: awx-secret-tls
  hostname: awx.example.com     👈👈👈
...
```
Is there a way to specify an additional hostname? I know that traefik itself can handle this in the docker environment, but I'm not sure if this is possible in this context.

Thanks and best regards

Jens

**Comment by kurokobo** [comment]
@jheinitz 
Hi, 

I've never tried that, but the customization of Ingress resource by using AWX Operator is highly limited since AWX Operator just _templates_ manifest based on [this file: `ingress.yaml.j2`](https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/ingress.yaml.j2).

So, if your requirements can be achieved by manually created Ingress, I recommend you to:
- Do not create Ingress using AWX Operator. Remove `ingress_*` and `hostname`.
- Create Ingress resource manually.

Maybe I don't fully understand your requirements, but hou about create the following resource, for example?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-custom-ingress
  namespace: awx
spec:
  rules:
    - host: ansible.example.com
      http:
        paths:
          - backend:
              service:
                name: awx-service
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: ansible01.example.com
      http:
        paths:
          - backend:
              service:
                name: awx-service
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: ansible02.example.com
      http:
        paths:
          - backend:
              service:
                name: awx-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ansible.example.com
        - ansible01.example.com
        - ansible02.example.com
      secretName: awx-secret-tls
```
