### ISSUE TITLE
Ldaps wit ca self signed

### ISSUE THREAD

**Issue by fferraro87** [kurokobo/awx-on-k3s#90]
## Environment

- OS: Ubuntu 20.04.4 LTS.
- Kubernetes/K3s: k3s version v1.22.7+k3s1
- AWX Operator: 0.22.0

## Description
Cannot use ldaps with ca self signed.
i've always same error on awx-web container :
```
2022-06-14 09:49:59,087 WARNING  [7364d930a2694d95b811887768349fc0] django_auth_ldap Caught LDAPError while authenticating fferraro87: SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'errno': 107, 'ctrls': [], 'info': 'Transport endpoint is not connected'})
```

## Step to Reproduce

1. i've added to kustomization.yaml : 
   ```
     - name: awx-custom-certs
    type: Opaque
    files: 
      - ldap-ca.crt=/root/francesco/awx-on-k3s/base/ca1.ad.francesco.it.pem
      - bundle-ca.crt=/root/francesco/awx-on-k3s/base/ca1.ad.francesco.it.pem
 
 and on awx.yaml
```

   ldap_cacert_secret: awx-custom-certs
  bundle_cacert_secret: awx-custom-certs

```
  2. kubectl apply -k base

On secrets, there are  

`awx-custom-certs                              Opaque                                2      10d`

```
root@automation:~/francesco/awx-on-k3s# kubectl describe secret awx-custom-certs -n awx
Name:         awx-custom-certs
Namespace:    awx
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
ldap-ca.crt:    2390 bytes
bundle-ca.crt:  2390 bytes
```


but i've always same error.
i've try also to disable on awx.yaml LDAPTLS_REQCERT with this :
```
spec:
 .
 .
 .   
  web_extra_env: |
    - name: LDAPTLS_REQCERT
      value: never
```
but still nothing, do you've an idea on how can i use ldaps?
thanks
